version: '3'

services: 
  oraclesrv:
    image: oracleinanutshell/oracle-xe-11g:latest
    ports: 
      - "1521:1521"
      - "5500:5500"
      - "8080:8080"
    volumes: 
      - /Users/nelson/docker/oracle/data:/opt/oracle/oradata
    networks: 
      - oracle-compose-network
    
networks: 
  oracle-compose-network:
    driver: bridge

# Login http://localhost:8080/apex/apex_admin with following credential:
# username: ADMIN
# password: admin

# Password for SYS & SYSTEM
# oracle