version: '3'

services: 
  mysqlsrv:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: "MySql2020!"
      MYSQL_DATABASE: "appdb"
    ports: 
      - "3306:3306"
    volumes: 
      - /Users/nelson/docker/mysql/data:/var/lib/mysql
    networks: 
      - mysql-compose-network
  
  adminer:
    image: adminer
    ports: 
      - 8080:8080
    networks: 
      - mysql-compose-network
    
networks: 
  mysql-compose-network:
    driver: bridge